name: Prettify Code

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
      - run: npm install prettier-plugin-tailwindcss

      - name: Prettier write
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
          commit_message: "automated: ran prettier write"
          prettier_plugins: "prettier-plugin-tailwindcss"
